const state={data:[],brand:'',ram:'',storage:'',min:null,max:null,only5g:false,onlyStock:false,quick:'all',search:'',sort:'price-desc',compare:new Set()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>n==null?'—':'Rs. '+Number(n).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const currentPrice=p=>Number(p.price||p.min_price||0);const specs=p=>({ram:p.ram||'',storage:p.storage||'',display:p.key_specs?.display||p.display||'',chipset:p.key_specs?.chipset||p.chipset||'',camera:p.key_specs?.camera||p.camera||'',battery:p.key_specs?.battery||p.battery||''});
const size=v=>{const m=String(v||'').match(/(\d+)\s*GB/i);return m?Number(m[1]):0};
function renderFilters(){const brands=[...new Set(state.data.map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b));const q=($('#brandSearch').value||'').toLowerCase();$('#brandList').innerHTML=brands.filter(b=>b.toLowerCase().includes(q)).map(b=>`<div class="brand-option ${state.brand===b?'active':''}" data-brand="${esc(b)}"><span>${esc(b)}</span><span>${state.data.filter(p=>p.brand===b).length}</span></div>`).join('');const rams=[...new Set(state.data.flatMap(p=>p.rams||[]))].filter(Boolean).sort((a,b)=>size(a)-size(b));const stores=[...new Set(state.data.flatMap(p=>p.storages||[]))].filter(Boolean).sort((a,b)=>size(a)-size(b));$('#ramFilters').innerHTML=rams.map(v=>`<button class="pill ${state.ram===v?'active':''}" data-ram="${esc(v)}">${esc(v)}</button>`).join('');$('#storageFilters').innerHTML=stores.map(v=>`<button class="pill ${state.storage===v?'active':''}" data-storage="${esc(v)}">${esc(v)}</button>`).join('')}
function matches(p){const text=[p.name,p.brand,p.chipset,p.display,...(p.variants||[]),...(p.rams||[]),...(p.storages||[])].join(' ').toLowerCase();if(state.search&&!text.includes(state.search.toLowerCase()))return false;if(state.brand&&p.brand!==state.brand)return false;if(state.ram&&!(p.rams||[]).includes(state.ram))return false;if(state.storage&&!(p.storages||[]).includes(state.storage))return false;if(state.min!=null&&currentPrice(p)<state.min)return false;if(state.max!=null&&currentPrice(p)>state.max)return false;if(state.only5g&&!p.is_5g)return false;if(state.onlyStock&&String(p.stock||'').toLowerCase()!=='in stock')return false;if(state.quick==='under-20000'&&currentPrice(p)>=20000)return false;if(state.quick==='under-50000'&&currentPrice(p)>=50000)return false;if(state.quick==='under-80000'&&currentPrice(p)>=80000)return false;if(state.quick==='iphone'&&p.brand!=='Apple')return false;if(state.quick==='5g'&&!p.is_5g)return false;if(state.quick==='top-rated'&&Number(p.rating||0)<4.5)return false;return true}
function sortData(a){const x=[...a];if(state.sort==='price-desc')return x.sort((a,b)=>currentPrice(b)-currentPrice(a));if(state.sort==='price-asc')return x.sort((a,b)=>currentPrice(a)-currentPrice(b));if(state.sort==='rating')return x.sort((a,b)=>Number(b.rating||0)-Number(a.rating||0));if(state.sort==='latest')return x.sort((a,b)=>String(b.launch_date||'').localeCompare(String(a.launch_date||'')));return x.sort((a,b)=>a.name.localeCompare(b.name))}
function card(p){const s=specs(p),selected=state.compare.has(p.id);return `<article class="card"><div class="card-media">${p.image?`<img loading="lazy" src="${esc(p.image)}" alt="${esc(p.name)}">`:`<div class="no-img">▱</div>`}<label class="compare-check" title="Compare"><input type="checkbox" data-compare="${esc(p.id)}" ${selected?'checked':''}></label>${p.stock?`<span class="stock">${esc(p.stock)}</span>`:''}</div><div class="card-body"><div class="brand-name">${esc(p.brand)}</div><h3>${esc(p.name)}</h3><div><span class="price">${money(currentPrice(p))}</span>${p.original_price&&p.original_price>currentPrice(p)?`<span class="old">${money(p.original_price)}</span>`:''}</div><div class="variant">${esc((p.variants||[]).slice(0,2).join(' • ')||'Variant details available')}</div><div class="spec-row"><div class="spec"><b>${esc(s.ram||'—')}</b><span>RAM</span></div><div class="spec"><b>${esc(s.storage||'—')}</b><span>Storage</span></div><div class="spec"><b>${esc(s.display||'—')}</b><span>Display</span></div></div>${p.rating?`<div class="rating">Expert rating <strong>★ ${esc(p.rating)}/5</strong></div>`:''}</div></article>`}
function render(){const filtered=sortData(state.data.filter(matches));$('#phoneCount').textContent=state.data.length.toLocaleString();$('#resultCount').textContent=filtered.length.toLocaleString();$('#grid').innerHTML=filtered.map(card).join('');$('#empty').classList.toggle('hidden',filtered.length>0);$('#compareCount').textContent=state.compare.size;$$('[data-compare]').forEach(x=>x.addEventListener('change',e=>{const id=e.target.dataset.compare;if(e.target.checked){if(state.compare.size>=3){e.target.checked=false;alert('Compare up to 3 phones.');return}state.compare.add(id)}else state.compare.delete(id);render()}))}
function clear(){state.brand=state.ram=state.storage='';state.min=state.max=null;state.only5g=state.onlyStock=false;state.quick='all';$('#minPrice').value='';$('#maxPrice').value='';$('#only5g').checked=false;$('#onlyStock').checked=false;$$('#quickFilters button').forEach(x=>x.classList.toggle('active',x.dataset.quick==='all'));renderFilters();render()}
function openCompare(){const ps=[...state.compare].map(id=>state.data.find(p=>p.id===id)).filter(Boolean);$('#compareBody').innerHTML=ps.length?`<table class="compare-table"><thead><tr><th>Feature</th>${ps.map(p=>`<th>${esc(p.name)}<br><b>${money(currentPrice(p))}</b></th>`).join('')}</tr></thead><tbody>${[['Brand','brand'],['RAM','ram'],['Storage','storage'],['Display','display'],['Chipset','chipset'],['Camera','camera'],['Battery','battery'],['5G','is_5g'],['Expert rating','rating'],['Stock','stock']].map(([label,key])=>`<tr><th>${label}</th>${ps.map(p=>`<td>${esc(key==='is_5g'?(p[key]?'Yes':'No'):key==='rating'?(p[key]?p[key]+'/5':'—'):p[key]||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty"><h3>No phones selected</h3><p>Tick the compare box on up to three cards.</p></div>';$('#comparePanel').classList.remove('hidden')}
function closeCompare(){$('#comparePanel').classList.add('hidden')}
async function init(){try{const r=await fetch('data.json?'+Date.now());const payload=await r.json();state.data=payload.products||[];$('#updated').textContent=payload.updated_at?`Updated ${new Date(payload.updated_at).toLocaleString()}`:'Catalog synced';renderFilters();render()}catch(e){$('#grid').innerHTML='<div class="loading">Catalog is being prepared. Refresh shortly.</div>';$('#updated').textContent='Waiting for first sync…'}}
$('#search').addEventListener('input',e=>{state.search=e.target.value;render()});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});$('#brandSearch').addEventListener('input',renderFilters);$('#brandList').addEventListener('click',e=>{const b=e.target.closest('[data-brand]')?.dataset.brand;if(!b)return;state.brand=state.brand===b?'':b;renderFilters();render()});$('#ramFilters').addEventListener('click',e=>{if(!e.target.dataset.ram)return;state.ram=state.ram===e.target.dataset.ram?'':e.target.dataset.ram;renderFilters();render()});$('#storageFilters').addEventListener('click',e=>{if(!e.target.dataset.storage)return;state.storage=state.storage===e.target.dataset.storage?'':e.target.dataset.storage;renderFilters();render()});$('#minPrice').addEventListener('input',e=>{state.min=Number(e.target.value)||null;render()});$('#maxPrice').addEventListener('input',e=>{state.max=Number(e.target.value)||null;render()});$('#only5g').addEventListener('change',e=>{state.only5g=e.target.checked;render()});$('#onlyStock').addEventListener('change',e=>{state.onlyStock=e.target.checked;render()});$('#quickFilters').addEventListener('click',e=>{const q=e.target.dataset.quick;if(!q)return;state.quick=q;$$('#quickFilters button').forEach(x=>x.classList.toggle('active',x.dataset.quick===q));render()});$('#clearAll').onclick=clear;$('#clearFilters').onclick=clear;$('#compareBtn').onclick=openCompare;$('#closeCompare').onclick=closeCompare;$('#comparePanel').addEventListener('click',e=>{if(e.target.id==='comparePanel')closeCompare()});init();
