/* Laxman Nepal PDF Tools — browser-side utilities */
(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const root = $('#pdf-app');
  if (!root) return;
  root.innerHTML = `
    <div class="pdf-app-head"><div><span class="app-kicker">BROWSER PDF LAB</span><h2>Work with your PDF</h2><p>Your files stay in your browser for these tools.</p></div><span class="privacy-pill">🔒 Local processing</span></div>
    <div class="pdf-tool-tabs">
      <button class="active" data-mode="merge">🧩 Merge</button><button data-mode="split">✂️ Split</button><button data-mode="rotate">🔄 Rotate</button><button data-mode="images">🖼️ Images → PDF</button>
    </div>
    <div class="pdf-workspace">
      <div class="drop-zone" id="drop"><input id="files" type="file" accept=".pdf,image/png,image/jpeg,image/webp" multiple hidden><div class="drop-icon">📄</div><strong id="drop-title">Drop PDF files here</strong><span id="drop-help">or click to choose files</span><button id="choose" type="button">Choose files</button></div>
      <div id="file-list" class="file-list"></div>
      <div id="mode-options" class="mode-options"></div>
      <div class="app-actions"><button id="clear" class="ghost" type="button">Clear</button><button id="run" class="primary" type="button">Create PDF →</button></div>
      <div id="status" class="app-status" aria-live="polite"></div>
    </div>`;
  const style=document.createElement('style'); style.textContent=`
    .pdf-app{margin-top:28px;border:1px solid #e4e7ec;border-radius:24px;background:#fff;box-shadow:0 18px 50px rgba(16,24,40,.08);overflow:hidden}.pdf-app-head{padding:24px;display:flex;justify-content:space-between;gap:15px;align-items:flex-start;border-bottom:1px solid #eaecf0}.app-kicker{font-size:10px;font-weight:900;letter-spacing:.12em;color:#ef4444}.pdf-app h2{margin:6px 0 4px;font-size:24px}.pdf-app p{margin:0;color:#667085;font-size:12px}.privacy-pill{padding:8px 11px;border:1px solid #d0d5dd;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.pdf-tool-tabs{display:flex;gap:7px;overflow:auto;padding:12px 18px;border-bottom:1px solid #eaecf0}.pdf-tool-tabs button{border:1px solid #e4e7ec;background:#fff;border-radius:999px;padding:9px 13px;font-size:12px;font-weight:800;white-space:nowrap;cursor:pointer}.pdf-tool-tabs button.active{background:#111827;color:#fff;border-color:#111827}.pdf-workspace{padding:22px}.drop-zone{min-height:180px;border:1.5px dashed #cfd4dc;border-radius:19px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;background:#fafafa;text-align:center;cursor:pointer;transition:.2s}.drop-zone.drag{border-color:#ef4444;background:#fff7f7}.drop-icon{font-size:38px}.drop-zone strong{font-size:15px}.drop-zone span{font-size:12px;color:#667085}.drop-zone button{margin-top:8px;border:1px solid #d0d5dd;background:#fff;border-radius:10px;padding:9px 13px;font-weight:800;cursor:pointer}.file-list{display:grid;gap:8px;margin-top:14px}.file-row{display:flex;align-items:center;gap:10px;padding:11px 13px;border:1px solid #eaecf0;border-radius:12px}.file-row span:nth-child(2){flex:1;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-row small{color:#667085}.remove-file{border:0;background:transparent;cursor:pointer;font-size:17px}.mode-options{margin-top:14px}.option-box{padding:13px;border:1px solid #eaecf0;border-radius:13px;display:flex;gap:12px;align-items:center;font-size:12px}.option-box input,.option-box select{margin-left:auto;padding:7px;border:1px solid #d0d5dd;border-radius:8px}.app-actions{display:flex;justify-content:space-between;margin-top:16px}.app-actions button{border-radius:11px;padding:10px 15px;font-weight:850;cursor:pointer}.primary{background:#111827;color:#fff;border:1px solid #111827}.ghost{background:#fff;border:1px solid #d0d5dd}.app-status{min-height:18px;margin-top:12px;text-align:center;font-size:12px;color:#667085}@media(max-width:600px){.pdf-app-head{display:block}.privacy-pill{display:inline-block;margin-top:12px}.pdf-workspace{padding:14px}}`; document.head.appendChild(style);
  let mode='merge', files=[];
  const input=$('#files'), list=$('#file-list'), opts=$('#mode-options'), status=$('#status');
  const lib=()=>window.PDFLib;
  function render(){list.innerHTML=files.map((f,i)=>`<div class="file-row"><span>📄</span><span>${f.name}</span><small>${(f.size/1024/1024).toFixed(2)} MB</small><button class="remove-file" data-i="${i}" aria-label="Remove">×</button></div>`).join('');list.querySelectorAll('.remove-file').forEach(b=>b.onclick=()=>{files.splice(+b.dataset.i,1);render()});}
  function options(){opts.innerHTML= mode==='split' ? '<div class="option-box"><span>Pages to extract</span><input id="pages" placeholder="e.g. 1,3-5"></div>' : mode==='rotate' ? '<div class="option-box"><span>Rotation</span><select id="rotation"><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div>' : ''; $('#run').textContent=mode==='images'?'Create PDF →':mode==='split'?'Split PDF →':mode==='rotate'?'Rotate PDF →':'Merge PDF →';}
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;files=[];render();$('#files').accept=mode==='images'?'image/png,image/jpeg,image/webp':'.pdf';$('#files').multiple=mode!=='split'&&mode!=='rotate';$('#drop-title').textContent=mode==='images'?'Drop images here':'Drop PDF files here';options()});
  $('#choose').onclick=e=>{e.stopPropagation();input.click()}; $('#drop').onclick=()=>input.click(); input.onchange=()=>{files=[...input.files];render()};
  ['dragenter','dragover'].forEach(e=>$('#drop').addEventListener(e,x=>{x.preventDefault();$('#drop').classList.add('drag')}));['dragleave','drop'].forEach(e=>$('#drop').addEventListener(e,x=>{x.preventDefault();$('#drop').classList.remove('drag')}));$('#drop').ondrop=e=>{files=[...e.dataTransfer.files];render()};
  $('#clear').onclick=()=>{files=[];input.value='';render();status.textContent=''};
  async function save(bytes,name){const blob=new Blob([bytes],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function pages(s){return s.split(',').flatMap(x=>{x=x.trim();if(!x)return[];if(x.includes('-')){let[a,b]=x.split('-').map(Number);return Array.from({length:b-a+1},(_,i)=>a+i)}return[Number(x)]}).filter(Number.isFinite)}
  $('#run').onclick=async()=>{status.textContent='Working…';try{if(!files.length)throw Error('Choose at least one file.');const P=lib();if(!P)throw Error('PDF engine is still loading. Please try again.');if(mode==='images'){const out=await P.PDFDocument.create();for(const f of files){const data=await f.arrayBuffer(), type=f.type;let img=type==='image/png'?await out.embedPng(data):await out.embedJpg(data);const page=out.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}await save(await out.save(),'images-to-pdf.pdf')}else{const src=await P.PDFDocument.load(await files[0].arrayBuffer()),out=await P.PDFDocument.create();if(mode==='merge'){for(const f of files){const d=await P.PDFDocument.load(await f.arrayBuffer()),copied=await out.copyPages(d,d.getPageIndices());copied.forEach(p=>out.addPage(p))}await save(await out.save(),'merged.pdf')}else if(mode==='split'){const wanted=pages($('#pages')?.value||'').map(n=>n-1).filter(n=>n>=0&&n<src.getPageCount());if(!wanted.length)throw Error('Enter page numbers, e.g. 1,3-5.');const copied=await out.copyPages(src,wanted);copied.forEach(p=>out.addPage(p));await save(await out.save(),'split.pdf')}else{const deg=Number($('#rotation').value);src.getPages().forEach(p=>p.setRotation(P.degrees(p.getRotation().angle+deg)));await save(await src.save(),'rotated.pdf')}}status.textContent='Done — your PDF has been downloaded.'}catch(e){status.textContent=e.message||'Something went wrong.'}};
  options();
})();