#!/usr/bin/env python3
"""Generate SEO-friendly static detail pages from jobs/jobs.json."""
from pathlib import Path
import json,re,shutil,html
ROOT=Path(__file__).resolve().parents[1]; JOBS=ROOT/"jobs/jobs.json"; OUT=ROOT/"jobs"
def slugify(s):
    s=re.sub(r"[^\w\s-]","",s.lower().strip(),flags=re.UNICODE)
    return re.sub(r"-+","-",re.sub(r"\s+","-",s))[:70].strip("-") or "job"
jobs=json.loads(JOBS.read_text(encoding="utf-8"))
active=set()
for j in jobs:
    slug=slugify(f'{j.get("title","job")}-{j.get("organization","")}')
    active.add(slug)
# Pages are generated by this script; stale generated pages are removed.
for d in OUT.iterdir():
    if d.is_dir() and (d/"index.html").exists():
        p=d/"index.html"
        try:
            if "<!-- GENERATED JOB PAGE -->" in p.read_text(encoding="utf-8") and d.name not in active: shutil.rmtree(d)
        except Exception: pass
print(f"Prepared {len(jobs)} job-page targets.")
