(()=>{'use strict';
const ICONS=['fa-table-cells','fa-calendar-days','fa-wand-magic-sparkles','fa-link','fa-book-open','fa-chart-line','fa-robot','fa-globe','fa-code','fa-bolt','fa-image','fa-file-lines'];
const RULES={AI:['ai','artificial','gpt','voice','tts','chatbot','machine'],Finance:['nepse','finance','stock','money','currency','bank'],Developer:['code','developer','github','html','css','javascript','api','json'],Education:['education','book','learn','typing','school','study'],Creative:['photo','image','video','music','lofi','design','creative'],Productivity:['excel','office','pdf','link','calendar','tool','generator'],Utility:['utility','converter','calculator','patro','weather','password']};
const FAV='laxman-app-favorites',REC='laxman-app-recent',THEME='laxman-app-theme';
const UI_VERSION_KEY='laxman-app-ui-version';
const UI_VERSIONS={v1:'/apps/launcher-ui-v1.css?v=2',v2:'/apps/launcher-ui-v2.css?v=3',v3:'/apps/launcher-ui-v3.css?v=2',v4:'/apps/launcher-ui-v4.css?v=2',v5:'/apps/launcher-ui-v5.css?v=2'};
const UI_LABELS={v1:'V1 · Classic',v2:'V2 · Marketplace',v3:'V3 · Dashboard',v4:'V4 · Storefront',v5:'V5 · Minimal'};
let allApps=[],activeCategory='All';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const favUrl=u=>{try{return 'https://www.google.com/s2/favicons?domain='+encodeURIComponent(new URL(u).hostname)+'&sz=128'}catch{return ''}};
const set=k=>new Set(JSON.parse(localStorage.getItem(k)||'[]'));
const save=(k,s)=>localStorage.setItem(k,JSON.stringify([...s].slice(0,30)));
const cat=x=>{const t=(x.name+' '+(x.description||'')+' '+(x.topics||[]).join(' ')).toLowerCase();for(const [k,v] of Object.entries(RULES))if(v.some(w=>t.includes(w)))return k;return 'Other'};
const localCatalog=()=>Array.isArray(window.LAXMAN_APP_CATALOG)?window.LAXMAN_APP_CATALOG.map((a,i)=>({...a,repo:a.repo||a.name,name:a.name,url:new URL(a.url,location.origin).href,description:a.description||'',topics:a.topics||[],stars:Number(a.stars||0),updated:a.updated||'',category:a.category&&a.category!=='Other'?a.category:cat(a),icon:a.icon||ICONS[i%ICONS.length],snapshot:a.snapshot||'/assets/app-snapshots/'+slug(a.name)+'.webp',fallback:a.fallback||'',favicon:a.favicon||'',featured:Boolean(a.featured)})):[]};
const dedupe=apps=>{const m=new Map();for(const a of apps){const key=(a.url||'').replace(/\/$/,'').toLowerCase();if(!key||key===location.origin+'/apps'||key===location.origin+'/apps/')continue;const old=m.get(key);if(!old||Number(a.stars||0)>Number(old.stars||0))m.set(key,a)}return [...m.values()]};
function visible(){const q=document.getElementById('app-search').value.trim().toLowerCase(),r=set(REC),f=set(FAV);let a=allApps.filter(x=>(activeCategory==='All'||x.category===activeCategory)&&[x.name,x.url,x.description,x.category].some(v=>String(v).toLowerCase().includes(q)));const s=document.getElementById('sort-apps').value;if(s==='updated')a.sort((x,y)=>new Date(y.updated||0)-new Date(x.updated||0));else if(s==='stars')a.sort((x,y)=>y.stars-x.stars);else if(s==='featured')a.sort((x,y)=>Number(y.featured)-Number(x.featured)||y.stars-x.stars);else if(s==='recent')a.sort((x,y)=>(r.has(y.repo)?0:1)-(r.has(x.repo)?0:1)||x.name.localeCompare(y.name));else a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function card(a){const f=set(FAV),fav=f.has(a.repo);let host='';try{host=new URL(a.url).hostname.replace(/^www\\./,'')}catch{};return '<a class="app-card" href="'+esc(a.url)+'" target="_blank" rel="noopener noreferrer" data-repo="'+esc(a.repo)+'"><button class="fav-btn '+(fav?'active':'')+'" type="button" aria-label="'+(fav?'Remove from favorites':'Add to favorites')+'"><i class="fa-solid fa-star"></i></button><div class="app-preview"><div class="preview-loading">Loading preview…</div><img class="app-snapshot" src="'+esc(a.snapshot)+'" data-fallback="'+esc(a.fallback)+'" alt="'+esc(a.name)+' homepage preview" loading="lazy" decoding="async" referrerpolicy="no-referrer"></div><div class="app-info"><span class="app-icon"><i class="fa-solid '+esc(a.icon)+'"></i><img src="'+esc(a.favicon||favUrl(a.url))+'" alt="" loading="lazy" onload="this.previousElementSibling.style.display=\'none\'" onerror="this.remove()"></span><span class="app-name-wrap"><span class="app-name">'+esc(a.name)+'</span><span class="app-open"><span class="app-category">'+esc(a.category)+'</span><span class="app-status"><span class="status-dot"></span>Live</span><span class="app-domain">'+esc(host)+'</span><i class="fa-solid fa-arrow-up-right-from-square"></i></span><span class="app-description">'+esc(a.description||'Open app')+'</span></span></div></a>'}
function renderCategories(){const cats=['All',...Object.keys(RULES),'Other'];document.getElementById('category-bar').innerHTML=cats.map(x=>'<button class="category-btn '+(x===activeCategory?'active':'')+'" data-cat="'+esc(x)+'">'+esc(x)+'</button>').join('');document.querySelectorAll('.category-btn').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderCategories();render()})}
function wire(){document.querySelectorAll('.app-card').forEach(c=>{const img=c.querySelector('.app-snapshot'),load=c.querySelector('.preview-loading'),fav=c.querySelector('.fav-btn');if(img.dataset.wired)return;img.dataset.wired='1';img.onload=()=>load.classList.add('hidden');img.onerror=()=>{if(img.dataset.fallback&&img.src!==img.dataset.fallback)img.src=img.dataset.fallback;else load.textContent='Preview unavailable'};fav.onclick=e=>{e.preventDefault();e.stopPropagation();const s=set(FAV),r=c.dataset.repo;s.has(r)?s.delete(r):s.add(r);save(FAV,s);fav.classList.toggle('active',s.has(r));fav.setAttribute('aria-label',s.has(r)?'Remove from favorites':'Add to favorites')};c.onclick=e=>{if(e.target.closest('.fav-btn'))return;const s=set(REC);s.delete(c.dataset.repo);save(REC,new Set([c.dataset.repo,...s]))}})}
function renderFeatured(){const sec=document.getElementById('featured-section'),q=document.getElementById('app-search').value.trim();if(q||activeCategory!=='All'){sec.style.display='none';return}sec.style.display='block';document.getElementById('featured-grid').innerHTML=[...allApps].sort((a,b)=>Number(b.featured)-Number(a.featured)||b.stars-a.stars).slice(0,4).map(x=>'<a class="featured-card" href="'+esc(x.url)+'" target="_blank" rel="noopener"><img class="featured-logo" src="'+esc(x.favicon||favUrl(x.url))+'" alt="" loading="lazy"><span><span class="featured-name">'+esc(x.name)+'</span><span class="featured-meta"><i class="fa-solid fa-star"></i> '+(x.stars||0)+' · '+esc(x.category)+'</span></span></a>').join('')}
function render(){const a=visible(),g=document.getElementById('apps-grid');document.getElementById('results-label').textContent=a.length+' '+(a.length===1?'app':'apps')+' shown';g.innerHTML=a.length?a.map(card).join(''):'<div class="empty" style="display:block">No apps found.</div>';wire();renderFeatured()}
function normalizeRepo(x){return {...x,repo:x.name,name:x.name.replace(/[-_]+/g,' '),url:x.homepage.trim(),description:x.description||'',topics:x.topics||[],stars:Number(x.stargazers_count||0),updated:x.updated_at||x.pushed_at||'',category:cat(x),icon:ICONS[Math.abs([...x.name].reduce((h,c)=>(h*31+c.charCodeAt(0))|0,0))%ICONS.length],snapshot:'/assets/app-snapshots/'+slug(x.name)+'.webp',fallback:'https://image.thum.io/get/width/1200/crop/900/noanimate/'+x.homepage.trim(),favicon:favUrl(x.homepage.trim()),featured:Number(x.stargazers_count||0)>0}}
async function enhanceFromGitHub(){try{const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),7000);const r=await fetch('https://api.github.com/users/LaxmanNepal/repos?per_page=100&sort=updated',{headers:{Accept:'application/vnd.github+json'},signal:ctl.signal,cache:'no-store'});clearTimeout(timer);if(!r.ok)throw new Error('GitHub API '+r.status);const repos=await r.json();const live=repos.filter(x=>!x.fork&&!x.archived&&x.homepage&&/^https?:\/\//i.test(x.homepage));const byUrl=new Map(live.map(x=>[x.homepage.replace(/\/$/,'').toLowerCase(),x]));allApps=allApps.map(a=>{const x=byUrl.get(a.url.replace(/\/$/,'').toLowerCase());return x?{...a,...normalizeRepo(x),repo:a.repo}:a});const known=new Set(allApps.map(a=>a.url.replace(/\/$/,'').toLowerCase()));for(const x of live){const u=x.homepage.replace(/\/$/,'').toLowerCase();if(!known.has(u)){allApps.push(normalizeRepo(x));known.add(u)}}allApps=dedupe(allApps);renderCategories();render()}catch(e){console.warn('Apps metadata update skipped:',e)}}
function renderUiSelector(){const host=document.getElementById('ui-version-wrap');if(!host)return;host.innerHTML='<label for="ui-version-select"><i class="fa-solid fa-palette"></i> UI</label><select id="ui-version-select" aria-label="Choose Apps UI version">'+Object.keys(UI_VERSIONS).map(v=>'<option value="'+v+'">'+esc(UI_LABELS[v]||v.toUpperCase())+'</option>').join('')+'</select>';const sel=host.querySelector('select');sel.value=document.documentElement.dataset.uiVersion||'v2';sel.onchange=()=>applyUiVersion(sel.value)}
function applyUiVersion(v){v=UI_VERSIONS[v]?v:'v2';const link=document.getElementById('launcher-ui');if(link)link.href=UI_VERSIONS[v];document.body.dataset.uiVersion=v;document.documentElement.dataset.uiVersion=v;localStorage.setItem(UI_VERSION_KEY,v);const sel=document.getElementById('ui-version-select');if(sel)sel.value=v;return v}
function applyTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem(THEME,t);document.getElementById('theme-btn').innerHTML=t==='dark'?'<i class="fa-solid fa-sun"></i>':'<i class="fa-solid fa-moon"></i>';document.getElementById('theme-color').content=t==='dark'?'#0b1020':'#111827'}
function boot(){applyUiVersion(localStorage.getItem(UI_VERSION_KEY)||document.body.dataset.uiVersion||'v2');renderUiSelector();allApps=dedupe(localCatalog());if(!allApps.length){document.getElementById('results-label').textContent='Apps unavailable';return}renderCategories();render();applyTheme(localStorage.getItem(THEME)||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));document.getElementById('theme-btn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');document.getElementById('app-search').oninput=render;document.getElementById('sort-apps').onchange=render;document.getElementById('grid-view').onclick=()=>{document.documentElement.dataset.view='grid';document.getElementById('grid-view').classList.add('active');document.getElementById('list-view').classList.remove('active')};document.getElementById('list-view').onclick=()=>{document.documentElement.dataset.view='list';document.getElementById('list-view').classList.add('active');document.getElementById('grid-view').classList.remove('active')};if('serviceWorker'in navigator)navigator.serviceWorker.register('/apps/sw.js?v=15',{scope:'/apps/'}).catch(()=>{});enhanceFromGitHub()}
window.LaxmanAppsUI={versions:Object.keys(UI_VERSIONS),getVersion:()=>document.documentElement.dataset.uiVersion||'v2',setVersion:applyUiVersion};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();