(()=>{
'use strict';
const API='https://api.github.com/users/LaxmanNepal/repos?per_page=100&sort=updated';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=u=>{try{const x=new URL(u);return (x.hostname.replace(/^www\./,'')+x.pathname.replace(/\/+$/,'')).toLowerCase()}catch{return''}};
const ago=d=>{const n=Math.max(0,Date.now()-new Date(d).getTime()),m=Math.floor(n/60000);if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<24)return h+'h ago';const days=Math.floor(h/24);if(days<30)return days+'d ago';const months=Math.floor(days/30);if(months<12)return months+'mo ago';return Math.floor(months/12)+'y ago'};
function style(){if(document.getElementById('lnx-details-style'))return;const s=document.createElement('style');s.id='lnx-details-style';s.textContent=`
.lnx-detail-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:14px 0}.lnx-detail-stat{padding:10px 11px;border:1px solid var(--border);border-radius:13px;background:color-mix(in srgb,var(--panel) 86%,var(--text));min-width:0}.lnx-detail-stat b{display:block;font-size:15px}.lnx-detail-stat span{display:block;color:var(--muted);font-size:9px;margin-top:3px;font-weight:750}.lnx-detail-desc{margin:0 0 14px;color:var(--muted);font-size:12px;line-height:1.55}.lnx-detail-actions{display:flex;flex-wrap:wrap;gap:8px}.lnx-detail-link{display:inline-flex;align-items:center;gap:6px;padding:9px 12px;border-radius:11px;border:1px solid var(--border);color:var(--text);text-decoration:none;font-size:11px;font-weight:850;background:var(--panel)}.lnx-detail-link.primary{background:var(--text);color:var(--panel);border-color:var(--text)}.lnx-detail-topics{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 14px}.lnx-topic{padding:4px 7px;border-radius:999px;background:var(--bg);color:var(--muted);font-size:9px;font-weight:800}.lnx-detail-loading{color:var(--muted);font-size:11px;padding:8px 0}@media(max-width:600px){.lnx-detail-grid{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(s)}
async function boot(){style();const overlay=document.querySelector('.lnx-overlay');if(!overlay)return;let repos=[];try{const r=await fetch(API,{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw 0;repos=await r.json()}catch{return}const map=new Map(repos.map(r=>[norm(r.homepage||''),r]));let last='';const enrich=()=>{if(!overlay.classList.contains('open'))return;const url=overlay.querySelector('.lnx-open')?.href||'';const repo=map.get(norm(url));if(!repo)return;const key=repo.html_url+'|'+(overlay.querySelector('.lnx-modal-title')?.textContent||'');if(key===last)return;last=key;const body=overlay.querySelector('.lnx-modal-body');if(!body)return;let box=body.querySelector('.lnx-detail-extra');if(!box){box=document.createElement('div');box.className='lnx-detail-extra';body.appendChild(box)}box.innerHTML='<div class="lnx-detail-loading">Loading GitHub details…</div>';const lang=repo.language||'Web';const topics=(repo.topics||[]).slice(0,8);box.innerHTML=`<div class="lnx-detail-grid"><div class="lnx-detail-stat"><b>★ ${Number(repo.stargazers_count||0).toLocaleString()}</b><span>Stars</span></div><div class="lnx-detail-stat"><b>${Number(repo.forks_count||0).toLocaleString()}</b><span>Forks</span></div><div class="lnx-detail-stat"><b>${esc(lang)}</b><span>Primary language</span></div><div class="lnx-detail-stat"><b>${esc(ago(repo.updated_at))}</b><span>Last updated</span></div></div>${repo.description?'<p class="lnx-detail-desc">'+esc(repo.description)+'</p>':''}${topics.length?'<div class="lnx-detail-topics">'+topics.map(t=>'<span class="lnx-topic">#'+esc(t)+'</span>').join('')+'</div>':''}<div class="lnx-detail-actions"><a class="lnx-detail-link primary" href="${esc(repo.html_url)}" target="_blank" rel="noopener"><i class="fa-brands fa-github"></i> Source</a>${repo.homepage?'<a class="lnx-detail-link" href="'+esc(repo.homepage)+'" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square"></i> Open app</a>':''}<a class="lnx-detail-link" href="${esc(repo.html_url)}/commits" target="_blank" rel="noopener"><i class="fa-solid fa-clock-rotate-left"></i> Changelog</a></div>`};new MutationObserver(enrich).observe(overlay,{attributes:true,attributeFilter:['class'],childList:true,subtree:true});enrich()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();