const $=id=>document.getElementById(id);
const input=$('fileInput'),drop=$('dropzone'),editor=$('editor'),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const maskCanvas=$('maskCanvas'),mctx=maskCanvas.getContext('2d',{willReadFrequently:true}),wrap=$('canvasWrap');
const beforeCanvas=$('beforeCanvas'),afterCanvas=$('afterCanvas'),bctx=beforeCanvas.getContext('2d'),actx=afterCanvas.getContext('2d');
let original=null,history=[],tool='brush',painting=false,last=null;
$('year').textContent=new Date().getFullYear();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function openPicker(){input.click()}
$('chooseBtn').onclick=openPicker;
drop.addEventListener('click',e=>{if(!e.target.closest('button'))openPicker()});
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();drop.classList.add('drag')}));
['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();drop.classList.remove('drag')}));
drop.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)loadFile(f)});
input.addEventListener('change',()=>{const f=input.files?.[0];if(f)loadFile(f);input.value='' });
function loadFile(file){if(!file.type.startsWith('image/'))return alert('Please choose an image file.');const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;maskCanvas.width=canvas.width;maskCanvas.height=canvas.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0);mctx.clearRect(0,0,canvas.width,canvas.height);original=ctx.getImageData(0,0,canvas.width,canvas.height);history=[];$('undoBtn').disabled=true;$('fileName').textContent=file.name;$('imageInfo').textContent=` · ${im.naturalWidth} × ${im.naturalHeight}`;drop.hidden=true;editor.hidden=false;updateOverlay();updatePreviews()};im.onerror=()=>alert('The image could not be decoded by this browser.');im.src=r.result};r.readAsDataURL(file)}
function updateOverlay(){const r=canvas.getBoundingClientRect(),wr=wrap.getBoundingClientRect();maskCanvas.style.width=r.width+'px';maskCanvas.style.height=r.height+'px';maskCanvas.style.left=(r.left-wr.left)+'px';maskCanvas.style.top=(r.top-wr.top)+'px'}
window.addEventListener('resize',()=>{updateOverlay();syncCompare()});
function pos(e){const b=canvas.getBoundingClientRect();return{x:clamp((e.clientX-b.left)/b.width*canvas.width,0,canvas.width),y:clamp((e.clientY-b.top)/b.height*canvas.height,0,canvas.height)}}
function updateCursor(e){const c=$('cursor'),r=canvas.getBoundingClientRect(),wr=wrap.getBoundingClientRect(),s=Number($('brushSize').value)*r.width/canvas.width;c.hidden=false;c.style.width=s+'px';c.style.height=s+'px';c.style.left=(e.clientX-wr.left)+'px';c.style.top=(e.clientY-wr.top)+'px'}
function paint(e){const p=pos(e),size=Number($('brushSize').value);mctx.save();mctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';mctx.fillStyle='rgba(225,29,72,.72)';mctx.strokeStyle='rgba(225,29,72,.72)';mctx.lineCap='round';mctx.lineJoin='round';mctx.lineWidth=size;mctx.beginPath();mctx.arc(p.x,p.y,size/2,0,Math.PI*2);mctx.fill();if(last){mctx.beginPath();mctx.moveTo(last.x,last.y);mctx.lineTo(p.x,p.y);mctx.stroke()}mctx.restore();last=p}
canvas.addEventListener('pointerdown',e=>{if(!canvas.width)return;painting=true;canvas.setPointerCapture(e.pointerId);last=null;paint(e)});canvas.addEventListener('pointermove',e=>{updateCursor(e);if(painting)paint(e)});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>{painting=false;last=null}));canvas.addEventListener('mouseenter',e=>updateCursor(e));canvas.addEventListener('mouseleave',()=>{$('cursor').hidden=true});
function setTool(t){tool=t;$('brushTool').classList.toggle('active',t==='brush');$('eraserTool').classList.toggle('active',t==='eraser')}$('brushTool').onclick=()=>setTool('brush');$('eraserTool').onclick=()=>setTool('eraser');
$('brushSize').oninput=e=>$('brushOut').textContent=e.target.value;$('feather').oninput=e=>$('featherOut').textContent=e.target.value;$('strength').oninput=e=>$('strengthOut').textContent=e.target.value;$('clearMaskBtn').onclick=()=>{mctx.clearRect(0,0,canvas.width,canvas.height)};
function getMaskBounds(){const d=mctx.getImageData(0,0,canvas.width,canvas.height).data;let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1,count=0;for(let y=0;y<canvas.height;y+=2)for(let x=0;x<canvas.width;x+=2){if(d[(y*canvas.width+x)*4+3]>20){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++}}return count?{x:minX,y:minY,w:maxX-minX+1,h:maxY-minY+1,count}:null}
function autoDetect(){const W=canvas.width,H=canvas.height,maxW=900,scale=Math.min(1,maxW/W),w=Math.max(1,Math.round(W*scale)),h=Math.max(1,Math.round(H*scale));const t=document.createElement('canvas');t.width=w;t.height=h;const tc=t.getContext('2d',{willReadFrequently:true});tc.drawImage(canvas,0,0,w,h);const d=tc.getImageData(0,0,w,h).data;const zones=[[0,0,w*.42,h*.34],[w*.58,0,w*.42,h*.34],[0,h*.66,w*.42,h*.34],[w*.58,h*.66,w*.42,h*.34]];let best=null;for(const z of zones){const [zx,zy,zw,zh]=z;let score=0,n=0;for(let y=Math.floor(zy)+2;y<Math.min(h-2,zy+zh);y+=4)for(let x=Math.floor(zx)+2;x<Math.min(w-2,zx+zw);x+=4){const i=(y*w+x)*4,L=(d[i]+d[i+1]+d[i+2])/3,up=(d[((y-2)*w+x)*4]+d[((y-2)*w+x)*4+1]+d[((y-2)*w+x)*4+2])/3,left=(d[(y*w+x-2)*4]+d[(y*w+x-2)*4+1]+d[(y*w+x-2)*4+2])/3;score+=(L>205||L<50?1.1:0)+(Math.abs(L-up)+Math.abs(L-left)>115?.9:0);n++}score/=Math.max(1,n);if(!best||score>best.score)best={z,score}}if(!best)return;const [zx,zy,zw,zh]=best.z,bx=Math.round(zx/scale),by=Math.round(zy/scale),bw=Math.round(zw/scale),bh=Math.round(zh/scale);const rw=clamp(Math.round(bw*.34),Math.min(48,W),Math.max(55,Math.round(W*.16))),rh=clamp(Math.round(bh*.34),Math.min(42,H),Math.max(50,Math.round(H*.13)));let x=zx<w*.5?bx+bw-rw:bx,y=zy<h*.5?by+bh-rh:by;x=clamp(x,0,W-rw);y=clamp(y,0,H-rh);mctx.clearRect(0,0,W,H);mctx.fillStyle='rgba(225,29,72,.72)';mctx.fillRect(x,y,rw,rh);alert('Likely Gemini-logo area selected. Refine with Brush/Eraser before healing.');}
$('autoBtn').onclick=autoDetect;
function maskData(){return mctx.getImageData(0,0,canvas.width,canvas.height).data}
function sourceCanvas(){const s=document.createElement('canvas');s.width=canvas.width;s.height=canvas.height;s.getContext('2d').putImageData(ctx.getImageData(0,0,canvas.width,canvas.height),0,0);return s}
function candidateSources(mb){const{x,y,w,h}=mb,c=[],gap=Math.max(4,Math.round(Math.min(w,h)*.35));if(x-w-gap>=0)c.push({x:x-w-gap,y});if(x+w+gap+w<=canvas.width)c.push({x:x+w+gap,y});if(y-h-gap>=0)c.push({x,y:y-h-gap});if(y+h+gap+h<=canvas.height)c.push({x,y:y+h+gap});return c}
function avgBorderScore(data,mb,sx,sy){const{x,y,w,h}=mb,step=Math.max(3,Math.floor(Math.min(w,h)/24));let score=0,n=0;const sample=(a,b)=>{score+=Math.abs(data[a]-data[b])+Math.abs(data[a+1]-data[b+1])+Math.abs(data[a+2]-data[b+2]);n++};for(let k=0;k<w;k+=step){const tx=clamp(x+k,0,canvas.width-1),sx2=clamp(sx+k,0,canvas.width-1);if(y>0)sample(((y-1)*canvas.width+tx)*4,(sy*canvas.width+sx2)*4);if(y+h<canvas.height)sample(((y+h)*canvas.width+tx)*4,((sy+h-1)*canvas.width+sx2)*4)}for(let k=0;k<h;k+=step){const ty=clamp(y+k,0,canvas.height-1),sy2=clamp(sy+k,0,canvas.height-1);if(x>0)sample((ty*canvas.width+x-1)*4,(sy2*canvas.width+sx)*4);if(x+w<canvas.width)sample((ty*canvas.width+x+w)*4,(sy2*canvas.width+sx+w-1)*4)}return score/Math.max(1,n)}
function smartPatch(src,mb){const sctx=src.getContext('2d'),full=sctx.getImageData(0,0,canvas.width,canvas.height),candidates=candidateSources(mb);let best=candidates[0],bestScore=Infinity;for(const c of candidates){const sc=avgBorderScore(full.data,mb,c.x,c.y);if(sc<bestScore){bestScore=sc;best=c}}const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const o=out.getContext('2d');o.drawImage(src,0,0);if(best)o.drawImage(src,best.x,best.y,mb.w,mb.h,mb.x,mb.y,mb.w,mb.h);return out}
function edgePatch(src,mb){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const o=out.getContext('2d');o.drawImage(src,0,0);const{x,y,w,h}=mb,side=Math.max(2,Math.round(Math.min(w,h)*.28));if(y>=side)o.drawImage(src,x,y-side,w,side,x,y,w,h);else if(y+h+side<=canvas.height)o.drawImage(src,x,y+h,w,side,x,y,w,h);else if(x>=side)o.drawImage(src,x-side,y,side,h,x,y,w,h);else if(x+w+side<=canvas.width)o.drawImage(src,x+w,y,side,h,x,y,w,h);return out}
function mirrorPatch(src,mb){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const o=out.getContext('2d');o.drawImage(src,0,0);const{x,y,w,h}=mb;o.save();o.translate(2*x+w,y);o.scale(-1,1);o.drawImage(src,x,y,w,h,x,y,w,h);o.restore();return out}
function texturePatch(src,mb){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const o=out.getContext('2d');o.drawImage(src,0,0);const{x,y,w,h}=mb,s=sourceCanvas(),offsets=[[-w,0],[w,0],[0,-h],[0,h],[-Math.round(w*.5),-Math.round(h*.5)],[Math.round(w*.5),Math.round(h*.5)]];for(const[dx,dy]of offsets){const sx=clamp(x+dx,0,canvas.width-w),sy=clamp(y+dy,0,canvas.height-h);o.globalAlpha=1/offsets.length;o.drawImage(s,sx,sy,w,h,x,y,w,h)}o.globalAlpha=1;return out}
function buildResult(mb){const src=sourceCanvas(),alg=$('algorithm').value;if(alg==='edge')return edgePatch(src,mb);if(alg==='mirror')return mirrorPatch(src,mb);if(alg==='texture')return texturePatch(src,mb);return smartPatch(src,mb)}
function applyMasked(result){const md=maskData(),base=ctx.getImageData(0,0,canvas.width,canvas.height),rd=result.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data,bd=base.data,str=Number($('strength').value)/100,feather=Number($('feather').value),mb=feather?getMaskBounds():null;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4,ma=md[i+3]/255;if(!ma)continue;let a=ma*str;if(mb&&feather){const edge=Math.min(x-mb.x,y-mb.y,mb.x+mb.w-1-x,mb.y+mb.h-1-y);a*=clamp(edge/feather,0,1)}for(let c=0;c<3;c++)bd[i+c]=Math.round(bd[i+c]*(1-a)+rd[i+c]*a)}ctx.putImageData(base,0,0)}
$('removeBtn').onclick=()=>{const mb=getMaskBounds();if(!mb)return alert('Paint over the Gemini logo first, or use Auto-detect.');history.push(ctx.getImageData(0,0,canvas.width,canvas.height));applyMasked(buildResult(mb));mctx.clearRect(0,0,canvas.width,canvas.height);$('undoBtn').disabled=false;updatePreviews()};
$('undoBtn').onclick=()=>{if(!history.length)return;ctx.putImageData(history.pop(),0,0);$('undoBtn').disabled=!history.length;updatePreviews()};
$('resetBtn').onclick=()=>{if(!original)return;history=[];ctx.putImageData(original,0,0);mctx.clearRect(0,0,canvas.width,canvas.height);$('undoBtn').disabled=true;updatePreviews()};
function updatePreviews(){if(!original)return;beforeCanvas.width=canvas.width;beforeCanvas.height=canvas.height;afterCanvas.width=canvas.width;afterCanvas.height=canvas.height;bctx.putImageData(original,0,0);actx.drawImage(canvas,0,0);syncCompare()}
function syncCompare(){const v=Number($('compareRange').value),line=document.querySelector('.compare-line');afterCanvas.style.clipPath=`inset(0 ${100-v}% 0 0)`;if(line)line.style.left=v+'%';$('previewLabel').textContent=`${v}% after`}
$('compareRange').oninput=syncCompare;
const mobile=$('gb-mobile');mobile?.addEventListener('click',()=>{$('.gb-menu')?.classList.toggle('open')});$('gb-search-input')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.currentTarget.value.trim())location.href='/blog/?q='+encodeURIComponent(e.currentTarget.value.trim())});