(()=>{
'use strict';
const $=id=>document.getElementById(id); const C=$('canvas'), M=$('maskCanvas'), W=$('canvasWrap'), mc=M?.getContext('2d',{willReadFrequently:true}); if(!C||!M||!mc)return;
const state={format:'png',quality:.92,cancel:false};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toast(msg){let t=$('v5toast');if(!t){t=document.createElement('div');t.id='v5toast';t.className='v5-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
const style=document.createElement('style');style.textContent=`.v5-panel{display:grid;grid-template-columns:1fr;gap:10px;margin:0 18px 16px;padding:14px;border:1px solid #e5e7eb;border-radius:12px;background:#fafafa}.v5-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.v5-row strong{font-size:11px}.v5-row button,.v5-row select{min-height:38px;border:0;border-radius:8px;padding:8px 11px;font-size:11px;font-weight:800;background:#eee;cursor:pointer}.v5-row button.active{background:#111;color:#fff}.v5-toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,20px);opacity:0;pointer-events:none;background:#111;color:#fff;padding:10px 14px;border-radius:999px;font-size:11px;font-weight:800;z-index:9999;transition:.2s}.v5-toast.show{opacity:1;transform:translate(-50%,0)}.v5-processing{position:absolute;inset:0;background:rgba(17,17,17,.72);display:grid;place-items:center;color:#fff;z-index:20}.v5-processing div{text-align:center;background:rgba(0,0,0,.65);padding:18px 22px;border-radius:14px;min-width:210px}.v5-processing b{display:block;font-size:13px;margin-bottom:8px}.v5-processing span{font-size:11px;color:#ddd}@media(max-width:600px){.v5-panel{margin:0 10px 12px}.v5-row>*{flex:1}.v5-row strong{flex-basis:100%}}`;document.head.appendChild(style);
const editor=$('editor'); if(editor){const controls=$('.controls');const panel=document.createElement('div');panel.className='v5-panel';panel.innerHTML=`<div class="v5-row"><strong>V5 Export</strong><button id="v5png" class="active">PNG</button><button id="v5jpg">JPG</button><button id="v5webp">WEBP</button><select id="v5quality" aria-label="Export quality"><option value=".98">98% quality</option><option value=".92" selected>92% quality</option><option value=".82">82% quality</option><option value=".70">70% quality</option></select><button id="v5download">Export</button></div><div class="v5-row"><strong>V5 View</strong><button id="v5full"><i class="fa-solid fa-expand"></i> Fullscreen</button><button id="v5clear">Clear mask</button><button id="v5cancel" disabled>Cancel processing</button><span id="v5status" style="font-size:10px;color:#6b7280">Shape-aware detection ready</span></div>`;controls?.before(panel)}
let processing=false;
function setExport(f){state.format=f;['png','jpg','webp'].forEach(x=>$('v5'+x)?.classList.toggle('active',x===f))}
['png','jpg','webp'].forEach(f=>$('v5'+f)?.addEventListener('click',()=>setExport(f)));$('v5quality')?.addEventListener('change',e=>state.quality=+e.target.value);
$('v5full')?.addEventListener('click',async()=>{try{await W.requestFullscreen()}catch{toast('Fullscreen is not available here')}});$('v5clear')?.addEventListener('click',()=>{mc.clearRect(0,0,C.width,C.height);toast('Mask cleared')});
function shapeDetect(){if(!C.width)return;const w=C.width,h=C.height;const candidates=[['top-left',0,0],['top-right',w,0],['bottom-left',0,h],['bottom-right',w,h]];const d=C.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h).data;let best=null;
function scoreCorner(cx,cy){const rw=Math.min(w*.22,Math.max(110,w*.12)),rh=Math.min(h*.18,Math.max(90,h*.10));const x0=cx?Math.max(0,w-rw):0,y0=cy?Math.max(0,h-rh):0;let edge=0,bright=0,n=0;for(let y=y0+4;y<y0+rh-4;y+=6)for(let x=x0+4;x<x0+rw-4;x+=6){const i=(y*w+x)*4,L=(d[i]+d[i+1]+d[i+2])/3,dx=Math.abs(L-(d[(y*w+x-3)*4]+d[(y*w+x-3)*4+1]+d[(y*w+x-3)*4+2])/3),dy=Math.abs(L-(d[((y-3)*w+x)*4]+d[((y-3)*w+x)*4+1]+d[((y-3)*w+x)*4+2])/3);edge+=dx+dy;bright+=(L>220||L<35)?1:0;n++}return(edge/n)+bright/n*45}
for(const c of candidates){const s=scoreCorner(c[1],c[2]);if(!best||s>best.s)best={c,s}}if(!best)return;const rw=clamp(Math.round(w*.11),60,Math.min(260,w)),rh=clamp(Math.round(h*.075),48,Math.min(180,h));const pad=Math.round(Math.min(w,h)*.012);let x=best.c[1]?w-rw-pad:pad,y=best.c[2]?h-rh-pad:pad;x=clamp(x,0,w-rw);y=clamp(y,0,h-rh);mc.clearRect(0,0,w,h);mc.fillStyle='rgba(225,29,72,.78)';const r=Math.min(rw,rh)*.18;mc.beginPath();mc.moveTo(x+r,y);mc.lineTo(x+rw-r,y);mc.lineTo(x+rw,y+r);mc.lineTo(x+rw,y+rh-r);mc.lineTo(x+rw-r,y+rh);mc.lineTo(x+r,y+rh);mc.lineTo(x,y+rh-r);mc.lineTo(x,y+r);mc.closePath();mc.fill();$('v5status').textContent=`Detected ${best.c[0]} · review mask`;toast('Shape-aware logo region selected')}
$('autoBtn').onclick=shapeDetect;
function getMask(){return mc.getImageData(0,0,C.width,C.height)}
function progress(on,text='Processing…',pct=0){const p=$('progress');if(!p)return;p.hidden=!on;if($('progressBar'))$('progressBar').style.width=pct+'%';if($('progressText'))$('progressText').textContent=text}
function neighborInpaint(mask,done){if(processing)return;processing=true;state.cancel=false;$('v5cancel').disabled=false;progress(true,'Preparing local inpaint…',2);const ctx=C.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,C.width,C.height),src=new Uint8ClampedArray(img.data),d=mask.data,W=C.width,H=C.height;const alpha=new Uint8Array(W*H);for(let i=0;i<W*H;i++)alpha[i]=d[i*4+3];
let maxR=12;const bounds=(()=>{let x0=W,y0=H,x1=0,y1=0;for(let y=0;y<H;y+=2)for(let x=0;x<W;x+=2)if(alpha[y*W+x]>20){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}return x1?{x0,y0,x1,y1}:null})();if(!bounds){finish();return}
const out=new Uint8ClampedArray(src);let y=0;function chunk(){const end=Math.min(H,y+Math.max(3,Math.floor(140000/W)));for(;y<end;y++){for(let x=0;x<W;x++){const id=y*W+x;if(alpha[id]<20)continue;let sr=0,sg=0,sb=0,n=0;for(let r=1;r<=maxR&&n<10;r++){const pts=[[x-r,y],[x+r,y],[x,y-r],[x,y+r]];for(const [px,py]of pts){if(px<0||py<0||px>=W||py>=H)continue;const j=py*W+px;if(alpha[j]<20){const k=j*4;sr+=src[k];sg+=src[k+1];sb+=src[k+2];n++;if(n>=10)break}}}if(n){const k=id*4;out[k]=sr/n;out[k+1]=sg/n;out[k+2]=sb/n}}}const pct=2+Math.round(y/H*94);progress(true,`Healing locally… ${pct}%`,pct);if(state.cancel){processing=false;$('v5cancel').disabled=true;progress(false);toast('Processing cancelled');return}if(y<H)requestAnimationFrame(chunk);else{img.data.set(out);ctx.putImageData(img,0,0);finish()}}function finish(){processing=false;$('v5cancel').disabled=true;progress(false);$('v5status').textContent='Local inpaint complete';if(typeof updatePreviews==='function')updatePreviews();toast('Healing complete')}}chunk()}
$('v5cancel')?.addEventListener('click',()=>state.cancel=true);
$('removeBtn').onclick=()=>{const mask=getMask();let n=0;for(let i=3;i<mask.data.length;i+=4)if(mask.data[i]>20)n++;if(!n){toast('Paint or auto-detect a mask first');return}neighborInpaint(mask)};
$('v5download')?.addEventListener('click',()=>{if(!C.width)return;const type=state.format==='jpg'?'image/jpeg':state.format==='webp'?'image/webp':'image/png';const quality=state.format==='png'?undefined:state.quality;C.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`laxman-gemini-remover.${state.format==='jpg'?'jpg':state.format}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`Exported ${state.format.toUpperCase()}`)},type,quality)});
const oldReset=$('resetBtn')?.onclick;$('resetBtn')?.addEventListener('click',()=>{$('v5status').textContent='Reset complete'});
window.addEventListener('beforeunload',()=>{if(processing)state.cancel=true});
})();
