(()=>{
'use strict';
const $=id=>document.getElementById(id), C=$('canvas'), M=$('maskCanvas'), W=$('canvasWrap');
if(!C||!M||!W)return;
const mc=M.getContext('2d',{willReadFrequently:true});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sleep=()=>new Promise(r=>requestAnimationFrame(r));
const state={cancel:false,running:false,mode:'balanced',radius:28,patch:7};
function toast(msg){let t=$('v6toast');if(!t){t=document.createElement('div');t.id='v6toast';t.className='v6-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2400)}
const css=document.createElement('style');css.textContent=`.v6-panel{margin:0 18px 16px;padding:14px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;display:grid;gap:10px}.v6-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.v6-row strong{font-size:11px;margin-right:2px}.v6-row button,.v6-row select{min-height:38px;border:0;border-radius:9px;padding:8px 11px;font:800 11px inherit;background:#f0f0f0;color:#111;cursor:pointer}.v6-row button.active{background:#111;color:#fff}.v6-note{font-size:10px;color:#6b7280;line-height:1.45}.v6-toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,18px);opacity:0;pointer-events:none;background:#111;color:#fff;padding:10px 15px;border-radius:999px;font-size:11px;font-weight:800;z-index:99999;transition:.2s}.v6-toast.show{opacity:1;transform:translate(-50%,0)}@media(max-width:600px){.v6-panel{margin:0 10px 12px}.v6-row>*{flex:1}.v6-row strong{flex-basis:100%}}`;document.head.appendChild(css);
const editor=$('editor'), controls=$('.controls');
if(editor&&controls){const p=document.createElement('section');p.className='v6-panel';p.innerHTML=`<div class="v6-row"><strong>V6 Restoration</strong><button id="v6conservative">Conservative</button><button id="v6balanced" class="active">Balanced</button><button id="v6strong">Strong</button><select id="v6radius" aria-label="Search radius"><option value="18">Near · 18px</option><option value="28" selected>Balanced · 28px</option><option value="42">Wide · 42px</option></select></div><div class="v6-row"><strong>Mask tools</strong><button id="v6invert">Invert mask</button><button id="v6refine">Refine mask</button><button id="v6maskonly">Mask preview</button></div><div class="v6-note">V6 uses patch-guided local reconstruction: it searches nearby clean patches and blends the best boundary match instead of averaging every masked pixel. It remains fully browser-side; no AI model or image upload is used.</div>`;controls.before(p)}
function getMask(){return mc.getImageData(0,0,C.width,C.height)}
function setProgress(on,text,pct=0){const p=$('progress');if(!p)return;p.hidden=!on;if($('progressBar'))$('progressBar').style.width=pct+'%';if($('progressText'))$('progressText').textContent=text}
function maskAlpha(){const d=getMask().data,a=new Uint8Array(C.width*C.height);for(let i=0,j=3;i<a.length;i++,j+=4)a[i]=d[j]>20?255:0;return a}
function refineMask(){if(!C.width)return;const w=C.width,h=C.height,a=maskAlpha(),out=new Uint8Array(a);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)n+=a[(y+dy)*w+x+dx]>0;out[y*w+x]=(a[y*w+x]&&n>=3)||(n>=7)?255:0}const img=mc.createImageData(w,h);for(let i=0,j=0;i<out.length;i++,j+=4){img.data[j]=225;img.data[j+1]=29;img.data[j+2]=72;img.data[j+3]=out[i]?170:0}mc.putImageData(img,0,0);toast('Mask refined');}
function invertMask(){const img=mc.getImageData(0,0,C.width,C.height);for(let i=3;i<img.data.length;i+=4)img.data[i]=img.data[i]>20?0:150;mc.putImageData(img,0,0);toast('Mask inverted')}
function maskPreview(){M.style.opacity=M.style.opacity==='1'?'0':'1';toast(M.style.opacity==='1'?'Mask preview on':'Mask preview off')}
$('v6invert')?.addEventListener('click',invertMask);$('v6refine')?.addEventListener('click',refineMask);$('v6maskonly')?.addEventListener('click',maskPreview);$('v6radius')?.addEventListener('change',e=>state.radius=+e.target.value);
['conservative','balanced','strong'].forEach(mode=>$('v6'+mode)?.addEventListener('click',()=>{state.mode=mode;['conservative','balanced','strong'].forEach(x=>$('v6'+x)?.classList.toggle('active',x===mode));state.patch=mode==='conservative'?5:mode==='strong'?9:7;toast(`${mode[0].toUpperCase()+mode.slice(1)} restoration selected`)}));
function autoV6(){if(!C.width)return;const w=C.width,h=C.height,ctx=C.getContext('2d',{willReadFrequently:true}),im=ctx.getImageData(0,0,w,h).data;let best=null;for(const [name,cx,cy] of [['top-left',0,0],['top-right',w,0],['bottom-left',0,h],['bottom-right',w,h]]){const rw=clamp(w*.16,90,Math.min(360,w)),rh=clamp(h*.11,70,Math.min(240,h)),x0=cx?Math.max(0,w-rw):0,y0=cy?Math.max(0,h-rh):0;let score=0,count=0;for(let y=y0+3;y<y0+rh-3;y+=4)for(let x=x0+3;x<x0+rw-3;x+=4){const i=(y*w+x)*4,L=.299*im[i]+.587*im[i+1]+.114*im[i+2];const q=(y*w+x+2)*4,Lx=.299*im[q]+.587*im[q+1]+.114*im[q+2];const q2=((y+2)*w+x)*4,Ly=.299*im[q2]+.587*im[q2+1]+.114*im[q2+2];score+=Math.abs(L-Lx)+Math.abs(L-Ly);count++}score/=count;if(!best||score>best.score)best={name,cx,cy}}const rw=clamp(w*.105,56,230),rh=clamp(h*.07,44,155),pad=Math.round(Math.min(w,h)*.012);let x=best.cx?w-rw-pad:pad,y=best.cy?h-rh-pad:pad;x=clamp(x,0,w-rw);y=clamp(y,0,h-rh);mc.clearRect(0,0,w,h);mc.fillStyle='rgba(225,29,72,.76)';mc.beginPath();const r=Math.min(rw,rh)*.2;mc.moveTo(x+r,y);mc.lineTo(x+rw-r,y);mc.lineTo(x+rw,y+r);mc.lineTo(x+rw,y+rh-r);mc.lineTo(x+rw-r,y+rh);mc.lineTo(x+r,y+rh);mc.lineTo(x,y+rh-r);mc.lineTo(x,y+r);mc.closePath();mc.fill();refineMask();toast(`V6 detected ${best.name} · mask refined`)}
$('autoBtn').onclick=autoV6;
function boundary(a,w,h){const b=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const id=y*w+x;if(!a[id])continue;if(!a[id-1]||!a[id+1]||!a[id-w]||!a[id+w])b.push(id)}return b}
function patchError(src,a,w,h,tx,ty,sx,sy,p){let e=0,n=0;for(let dy=-p;dy<=p;dy+=2)for(let dx=-p;dx<=p;dx+=2){const x=tx+dx,y=ty+dy,xx=sx+dx,yy=sy+dy;if(x<0||y<0||xx<0||yy<0||x>=w||y>=h||xx>=w||yy>=h)continue;if(a[y*w+x]){const k=(y*w+x)*4,k2=(yy*w+xx)*4;e+=Math.abs(src[k]-src[k2])+Math.abs(src[k+1]-src[k2+1])+Math.abs(src[k+2]-src[k2+2]);n++}}return n?e/n:1e9}
async function restore(){if(state.running)return;const m=getMask(),a=new Uint8Array(C.width*C.height);for(let i=0,j=3;i<a.length;i++,j+=4)a[i]=m.data[j]>20?255:0;const count=a.reduce((s,v)=>s+(v?1:0),0);if(!count){toast('Paint or auto-detect a mask first');return}state.running=true;state.cancel=false;const w=C.width,h=C.height,ctx=C.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,w,h),src=new Uint8ClampedArray(img.data),out=new Uint8ClampedArray(src),bd=boundary(a,w,h);if(!bd.length){state.running=false;return}setProgress(true,'V6 analysing clean patches…',3);
const radius=state.radius,p=state.patch,step=Math.max(1,Math.floor(bd.length/700));let done=0;for(let bi=0;bi<bd.length;bi+=step){if(state.cancel)break;const end=Math.min(bd.length,bi+step);for(let z=bi;z<end;z++){const id=bd[z],x=id%w,y=(id/w)|0;let best={e:1e9,x,y};for(let sy=Math.max(p,y-radius);sy<=Math.min(h-p-1,y+radius);sy+=Math.max(3,p)){for(let sx=Math.max(p,x-radius);sx<=Math.min(w-p-1,x+radius);sx+=Math.max(3,p)){const sid=sy*w+sx;if(a[sid])continue;const e=patchError(src,a,w,h,x,y,sx,sy,p);if(e<best.e)best={e,x:sx,y:sy}}}const k=id*4,k2=(best.y*w+best.x)*4;const blend=state.mode==='conservative'?.72:state.mode==='strong'?.98:.88;out[k]=src[k]*(1-blend)+src[k2]*blend;out[k+1]=src[k+1]*(1-blend)+src[k2+1]*blend;out[k+2]=src[k+2]*(1-blend)+src[k2+2]*blend}done=end;setProgress(true,`V6 reconstructing… ${Math.round(3+done/bd.length*82)}%`,3+done/bd.length*82);await sleep()}
if(!state.cancel){for(let y=0;y<h;y++){for(let x=0;x<w;x++){const id=y*w+x;if(!a[id])continue;let sr=0,sg=0,sb=0,n=0;for(let r=1;r<=p+2&&n<8;r++){for(const [dx,dy]of [[-r,0],[r,0],[0,-r],[0,r]]){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=w||yy>=h)continue;const q=yy*w+xx;if(!a[q]){const k=q*4;sr+=out[k];sg+=out[k+1];sb+=out[k+2];n++}}}if(n){const k=id*4;const blend=state.mode==='conservative'?.55:state.mode==='strong'?.9:.72;out[k]=out[k]*(1-blend)+(sr/n)*blend;out[k+1]=out[k+1]*(1-blend)+(sg/n)*blend;out[k+2]=out[k+2]*(1-blend)+(sb/n)*blend}}if(y%18===0){setProgress(true,`V6 blending texture… ${Math.round(85+y/h*14)}%`,85+y/h*14);await sleep()}}img.data.set(out);ctx.putImageData(img,0,0);if(typeof updatePreviews==='function')updatePreviews();toast('V6 restoration complete')}else toast('V6 processing cancelled');state.running=false;setProgress(false,'',0)}
$('removeBtn').onclick=restore;window.addEventListener('beforeunload',()=>state.cancel=true);
})();
